apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: a6j0n/backend:latest 
          env:
            - name: DOCDB_ENDPOINT
              value: "mongo-service"
            - name: JWT_SECRET 
              value: "piyush"
            - name: PORT
              value: "5000"
            - name: MONGO_INITDB_ROOT_USERNAME 
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: MONGO_INITDB_ROOT_USERNAME 
            - name: MONGO_INITDB_ROOT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE 
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: MONGO_INITDB_DATABASE 
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

