apiVersion: v1
data:
  MONGO_INITDB_DATABASE: Y2hhdGFwcA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-creds
